# stop apache because debian thinks it is a desktop
- name: stop apache
  service: name=apache2 state=stopped   

# stop smokeping until we configure it too
- name: stop smokeping
  service: name=smokeping state=stopped   

# bounce smokeping to load new configuration
- name: restart smokeping
  service: name=smokeping state=restarted   

# start apache and smokeping
- name: start all the things
  service: name={{ item }} state=started
  with_items:
    - apache2
    - smokeping
