---
# This playbook creates chicks home directory based on github

- hosts: $servername
  sudo: True
  tasks:
   - name: install rpm's needed by users
     apt: name={{ item }} state=present
     with_items:
      - git
      - mtr
      - screen
      - curl
      - wget
      - tmux
#      - whois
   - user: name=chicks uid=2015 comment="Christopher Hicks" generate_ssh_key=yes ssh_key_bits=4096
   - lineinfile: "dest=/etc/sudoers state=present line='chicks      ALL=(ALL)  NOPASSWD:ALL'"
   - shell: "if [[ -e /home/chicks/.git ]]; then false; fi"
     name: don't clobber git home already setup
   - git: repo=https://github.com/chicks-net/chicks-home.git dest=/home/chicks-gitclone update=yes
     name: git clone chicks-home
   - shell: "mv /home/chicks /home/chicks.orig && mv /home/chicks-gitclone /home/chicks && chown -R chicks.opsworks /home/chicks"
     name: swap chicks homes
   - shell: "if [[ -e /home/chicks.orig/.ssh/id_rsa ]]; then mv /home/chicks.orig/.ssh/id_rsa* /home/chicks/.ssh; fi"
     name: keep old ssh keys
   - command: restorecon -vR /home/chicks
   - command: chmod 700 /home/chicks/.ssh
   - command: chmod 600 /home/chicks/.ssh/config
