# build a DNS server slave
- hosts: c7d.fini.net
  vars:
    os_ignore_users:
      - lundin
      - chicks
    ssh_allow_root_with_key: true
    datadog_api_key: "{{ lookup('file', 'datadog.key') }}"
    datadog_config:
      tags: "region:digitalocean, env:dev"
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd' ]
    bind_zone_master_server_ip: 198.57.196.94
    bind_zone_domains:
      - name: 143.166.205.in-addr.arpa
      - name: almanacvapolitics.org
      - name: bayo.net
      - name: bettywalls.com
      - name: cac-medmal.com
      - name: chicks.net
      - name: cmanuel.com
      - name: cmanuel.net
      - name: cmanuel.org
      - name: denbighbaptist.com
      - name: denbighbaptist.org
      - name: einteractive.com
      - name: fini.net
      - name: finicase.com
      - name: finicase.net
      - name: finicase.org
      - name: finilever.com
      - name: finilever.net
      - name: finilever.org
      - name: frommyperspective.org
      - name: gamal.info
      - name: gaminggecko.net
      - name: gasp.org
      - name: in-fini-tees.com
      - name: in-fini-tees.net
      - name: infinitees.net
      - name: infinitees.org
      - name: ireserve.info
      - name: ireserve.us
      - name: jenniferwinter.com
      - name: jiffie.net
      - name: karlabranen.com
      - name: nodrats.com
      - name: partnersforjustice.com
      - name: partweb.com
      - name: patentattorneysearch.net
      - name: perlclass.com
      - name: perlclass.net
      - name: perlclass.org
      - name: perlclasses.com
      - name: perlclasses.net
      - name: perlclasses.org
      - name: politicsvirginia.org
      - name: qwp.org
      - name: seaprojects.org
      - name: vccinc.net
  pre_tasks:
  - name: get roles from galaxy
    shell: ansible-galaxy install "{{ item }}"
    delegate_to: 127.0.0.1
    loop:
      - dev-sec.os-hardening
      - dev-sec.ssh-hardening
      - Datadog.datadog
  roles:
    - common
    - homes
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - Datadog.datadog
    - bertvv.bind
