---
# This playbook sets up chicks' stock repos
- name: ssh recognize github.com
  authorized_key: user=chicks
                  key_options='host="192.30.252.128"'
                  key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

# clone once
- name: stat /home/chicks/Documents/dnetc
  stat: path="/home/chicks/Documents/dnetc"
  register: home_docs_dnetc
- name: git clone chicks-dnetc
  include: chicks-dnetc.yml
  when: home_docs_dnetc.stat.exists is defined and not home_docs_dnetc.stat.exists

- name: git clone quote-file
  git: repo=https://github.com/chicks-net/quote-file.git dest=/home/chicks/Documents/git/quote-file update=yes accept_hostkey=yes
