---
# This playbook sets up chicks' stock repos
# clone once
- name: stat /home/chicks/Documents/dnetc
  stat: path="/home/chicks/Documents/dnetc"
  register: home_docs_dnetc
- name: git clone chicks-dnetc
  include: chicks-dnetc.yml
  when: home_docs_dnetc.stat.exists is defined and not home_docs_dnetc.stat.exists

- name: git clone quote-file
  git: repo=https://github.com/chicks-net/quote-file.git dest=/home/chicks/Documents/git/quote-file update=yes accept_hostkey=yes
