---
- include: opsworks_json.yml

- include: packages.yml

- name: stat /root/.my.cnf
  stat: path="/root/.my.cnf"
  register: root_my_cnf
- name: include mysql if it hasn't already run
  include: mysql.yml
  when: root_my_cnf.stat.isreg is defined and not root_my_cnf.stat.isreg

- include: setup.yml

## much more to do
##
## - populate /etc/my.cnf
## - add OCS source
## - untar
