---
# This playbook sets up git repos
#
# clone once /etc/nagios
- name: stat /etc/nagios
  stat: path={{ nagios_etc }}
  register: etc_nagios
- name: stat /etc/nagios/.git
  stat: path="/etc/nagios/.git"
  register: etc_nagios_git

- name: mv rpm /etc/nagios out of the way
  shell: mv /etc/nagios /etc/nagios.orig_rpm
  when: etc_nagios.stat.exists is defined and etc_nagios.stat.exists and etc_nagios_git.stat.exists is defined and not etc_nagios_git.stat.exists

- name: /etc/nagios ownership
  file: path={{ nagios_etc }} state=directory owner=chicks group=nagios mode=0770

- name: git clone fini-nagios-conf
  become_user: chicks
  become: true
  git: repo=ssh://git@github.com/chicks-net/fini-nagios-conf.git dest={{ nagios_etc }}  update=no accept_hostkey=yes key_file=/home/chicks/.ssh/id_rsa

#
# plugins
#

- name: /usr/lib64/nagios/plugins ownership
  file: path={{ nagios_plugins }} state=directory owner=chicks group=nagios mode=0770

- name: /usr/lib64/nagios/plugins/eventhandlers should be gone
  file: path={{ nagios_plugins }}/eventhandlers state=absent

- name: git clone nagios-plugins
  become_user: chicks
  become: true
  git: repo=ssh://git@github.com/fini-net/nagios-plugins.git dest=/usr/lib64/nagios/plugins update=no accept_hostkey=yes key_file=/home/chicks/.ssh/id_rsa

- name: symlink plugins-conf
  file: src={{ nagios_plugins }}/config dest={{ nagios_etc }}/plugins-cfg state=link
