---
# This playbook installs epel-release and ansible
- name: install epel-release
  yum: name="epel-release" state=present
  when: ansible_distribution == 'CentOS'
#
- name: install rpm's only in EPEL
  yum: name={{ item }} state=present
  when: ansible_distribution == 'CentOS'
  with_items:
   - ansible
   - denyhosts
   - alpine
